name: peach_collector
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  analyzer: ^6.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
